
[block]
	#Allows the player to re-light certain blocks like Candles and Campfires (defined by the block using the `lit` blockstate) using torches or other items in the tag `vtweaks:ignition_item`
	enableTorchLighting = true
	enableCropTweaks = true
	#Trees fall down (like, actually not just like lumbering). Credit to Ternsip's impl (https://www.curseforge.com/minecraft/mc-mods/chopdown)
	enableTreeChopDown = true
	#The number of logs above the one broken to trigger the chopdown effect
	#Range: > 1
	chopDownLogRequirement = 3
	#The radius that this tweak will use to attempt to find leaves. Set this to a large number to detect larger trees (may cause lag)
	#Range: > 1
	chopdownSearchRadius = 64
	#Allows for uneaten cake to drop on break
	enableCakeDrop = true

[item]
	#Show food hunger & saturation on item hover
	#Allowed Values: NEVER, WITH_SHIFT, ALWAYS
	foodTooltipSetting = "WITH_SHIFT"
	#Show tool durability on item hover
	#Allowed Values: NEVER, WITH_SHIFT, ALWAYS
	durabilityTooltipSetting = "WITH_SHIFT"

[entity]
	#If set to "OWNER", this will prevent owners of pets from attacking their own pet. If set to "ALL", this prevents all players from attacking anyone's pet
	#Allowed Values: DISABLED, OWNER, ALL
	enablePetFriendlyFireTweak = "OWNER"
	#Prevents mobs from spawning above sea level unless it's a new moon
	enablePeacefulSurface = false
	#The lowest Y-level which mobs will be prevented from spawning
	#Range: > -2147483648
	peacefulSurfaceMinY = 60
	#When any Creeper (or entity with EntityType tag #forge:creepers) explodes, all blocks destroyed will plop back into place after a few seconds!
	ungriefCreepers = true
	#Allows chicken feathers to be plucked w/ shears
	enableFeatherPlucking = true
	#The amount of time (in Milliseconds) between plucks. Defaults to 10 minutes.
	#Range: 1 ~ 9223372036854775807
	featurePluckingCooldown = 600000
	#A data-driven way to make some special mobs with abilities, effects, specialized loot and more!
	enableChallengerMobs = true
	#This controls the overall chance for V-Tweaks to attempt converting a monster to a Challenger.
	#This chance is applied before any Challenger Mob weights or entity filters.
	#Range: 0.0 ~ 1.0
	challengerMobGlobalChance = 0.25

[player]
	#Feather Falling IV or above directs 100% of fall damage to boots
	enableFeatherFallTweak = true
	#Prevents any drops dropped by the player on death from despawning
	enablePlayerDeathDropSafety = true

[recipes]
	#Makes all anvil tool repairs always cost 1 level of XP
	enableCheapAnvilRepair = true
	#Allows you to throw things into specific fluids to convert them - by default this is just Concrete Powder this feature can be extended using Data Packs.
	enableFluidConversionRecipes = true

[world]
	#Disables thunder storms, fixing glitched lighting from thunder and other side-effects
	enableStormTweak = true

